version: "3.9"

services:
  btcgbp:
    build:
      context: .
    container_name: btcgbp
    volumes:
      - ./market/BTCGBP/config.json:/app/config.json
      - ./market/BTCGBP/pycryptobot.log:/app/pycryptobot.log
      - ./market/BTCGBP/graphs:/app/graphs
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      restart_policy:
        condition: on-failure

  ethgbp:
    build:
      context: .
    container_name: ethgbp
    volumes:
      - ./market/ETHGBP/config.json:/app/config.json
      - ./market/ETHGBP/pycryptobot.log:/app/pycryptobot.log
      - ./market/ETHGBP/graphs:/app/graphs
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      restart_policy:
        condition: on-failure

  adagbp:
    build:
      context: .
    container_name: adagbp
    volumes:
      - ./market/ADAGBP/config.json:/app/config.json
      - ./market/ADAGBP/pycryptobot.log:/app/pycryptobot.log
      - ./market/ADAGBP/graphs:/app/graphs
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      restart_policy:
        condition: on-failure